let jobs = [
  {
    id: 1,
    company: 'Photosnap',
    logo: './images/photosnap.svg',
    isNew: true,
    featured: true,
    position: 'Senior Front-end Developer',
    role: 'Front-end',
    level: 'Senior',
    postedAt: '1d ago',
    contract: 'Full Time',
    location: 'USA Only',
    languages: ['HTML', 'CSS', 'Javascript'],
    tools: ['React'],
  },
  {
    id: 2,
    company: 'Manage',
    logo: './images/manage.svg',
    isNew: true,
    featured: true,
    position: 'Fullstack Developer',
    role: 'Fullstack',
    level: 'Midweight',
    postedAt: '1d ago',
    contract: 'Part Time',
    location: 'Remote',
    languages: ['Python', 'Ruby'],
    tools: ['React'],
  },
  {
    id: 3,
    company: 'Account',
    logo: './images/account.svg',
    isNew: true,
    featured: false,
    position: 'Junior Front-end Developer',
    role: 'Front-end',
    level: 'Junior',
    postedAt: '2d ago',
    contract: 'Part Time',
    location: 'USA Only',
    languages: ['Javascript'],
    tools: ['React', 'Sass'],
  },
  {
    id: 4,
    company: 'MyHome',
    logo: './images/myhome.svg',
    isNew: true,
    featured: false,
    position: 'Junior Front-end Developer',
    role: 'Front-end',
    level: 'Junior',
    postedAt: '5d ago',
    contract: 'Contract',
    location: 'USA Only',
    languages: ['CSS', 'Javascript'],
    tools: ['Ruby On Rails', 'React'],
  },
  {
    id: 5,
    company: 'Loop Studios',
    logo: './images/loop-studios.svg',
    isNew: false,
    featured: true,
    position: 'Software Engineer',
    role: 'Fullstack',
    level: 'Midweight',
    postedAt: '1w ago',
    contract: 'Full Time',
    location: 'Worldwide',
    languages: ['Javascript'],
    tools: ['Ruby On Rails', 'Sass'],
  },
  {
    id: 6,
    company: 'FaceIt',
    logo: './images/faceit.svg',
    isNew: false,
    featured: false,
    position: 'Junior Backend Developer',
    role: 'Backend',
    level: 'Junior',
    postedAt: '2w ago',
    contract: 'Full Time',
    location: 'UK Only',
    languages: ['Ruby'],
    tools: ['Ruby On Rails'],
  },
  {
    id: 7,
    company: 'Shortly',
    logo: './images/shortly.svg',
    isNew: true,
    featured: true,
    position: 'Junior Developer',
    role: 'Front-end',
    level: 'Junior',
    postedAt: '2w ago',
    contract: 'Full Time',
    location: 'Worldwide',
    languages: ['HTML', 'Javascript'],
    tools: ['Sass'],
  },
  {
    id: 8,
    company: 'Insure',
    logo: './images/insure.svg',
    isNew: false,
    featured: false,
    position: 'Junior Front-end Developer',
    role: 'Front-end',
    level: 'Junior',
    postedAt: '2w ago',
    contract: 'Full Time',
    location: 'USA Only',
    languages: ['Javascript', 'Python'],
    tools: ['Vue', 'Sass'],
  },
  {
    id: 9,
    company: 'Eyecam Co.',
    logo: './images/eyecam-co.svg',
    isNew: false,
    featured: false,
    position: 'Full Stack Engineer',
    role: 'Fullstack',
    level: 'Midweight',
    postedAt: '3w ago',
    contract: 'Full Time',
    location: 'Worldwide',
    languages: ['Javascript', 'Python', 'HTML'],
    tools: ['Django', 'Ruby On Rails'],
  },
  {
    id: 10,
    company: 'The Air Filter Company',
    logo: './images/the-air-filter-company.svg',
    isNew: false,
    featured: true,
    position: 'Front-end',
    role: 'Front-end',
    level: 'Junior',
    postedAt: '1mo ago',
    contract: 'Part Time',
    location: 'Worldwide',
    languages: ['Javascript'],
    tools: ['React', 'Sass'],
  }
];

export default jobs;
